apiVersion: v1
kind: Pod
metadata:
  name: my-app
  namespace: kaniko
spec:
  securityContext:
    fsGroup: 65533 # to make SSH key readable
  containers:
  
    - name: my-app
      command: ['sh', '-c', 'echo The app is running! && ls -lah /etc/git-secret/ && cd / &&  ./git-sync ']            
      image: k8s.gcr.io/git-sync/git-sync:v3.4.0
      env:
        - name: GIT_SYNC_REPO
          value: git@github.com:fractiunate/private-project.git
        - name: GIT_SYNC_BRANCH
          value: main
        - name: GIT_SYNC_DEPTH
          value: "1"
        - name: GIT_SYNC_DEST
          value: "project"
        - name: GIT_SYNC_ONE_TIME
          value: "true"
        - name: GIT_SYNC_SSH
          value: "true"
      volumeMounts:
        - name: kanikogitsecret
          mountPath: "/etc/git-secret"
          readOnly: true
  restartPolicy: Never
  volumes:
    - name: kanikogitsecret
      secret:
        secretName: kanikogitsecret
        defaultMode: 256
