apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  securityContext:
    fsGroup: 65533 # to make SSH key readable
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      # image gcr.io/kaniko-project/executor:debug
      args:
        - "--context=dir:///workspace/project"
        - "--destination=fractiunate/kaniko-demo:latest"
        - "--dockerfile=Dockerfile"
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker/
        - name: content-from-git
          mountPath: /workspace
  initContainers:
    - name: git-sync
      image: k8s.gcr.io/git-sync:v3.1.5
      securityContext:
        runAsUser: 65533 # git-sync user
      volumeMounts:
        - name: content-from-git
          mountPath: /git
        - name: git-secret
          mountPath: "/etc/git-secret"
      args:
        - "--root=/git"
      env:
        - name: GIT_SYNC_REPO
          value: git@github.com:fractiunate/private-project.git
          # GIT_SYNC_REV the git revision (tag or hash) to check out
          # value: https://github.com/Imoustak/kaniko-build-demo.git
        - name: GIT_SYNC_BRANCH
          value: main
        - name: GIT_SYNC_DEPTH
          value: "1"
        - name: GIT_SYNC_DEST
          value: "project"
        - name: GIT_SYNC_ONE_TIME
          value: "true"
        - name: GIT_SYNC_SSH
          value: "true"
  restartPolicy: Never
  volumes:
    - name: ssh-key-volume
      secret:
        secretName: ssh-key-secret
        defaultMode: 256
    - name: content-from-git
      emptyDir: {}
    - name: git-secret
      secret:
        secretName: kaniko-git-secret # your-ssh-key
        defaultMode: 256
    - name: kaniko-secret
      secret:
        secretName: kaniko-docker-secrets
        items:
          - key: .dockerconfigjson
            path: config.json
