apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: App-of-Apps
spec:
  destination:
    namespace: kaniko
    server: "https://kubernetes.default.svc"
  source:
    path: ./argocd/argocd-apps/kaniko/
    repoURL: https://github.com/fractiunate/terraform-kaniko-k8s-service.git
    targetRevision: HEAD
  project: kaniko-project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true