apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kaniko-workload-0
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: kaniko-project
  source:
    path: ./kaniko/latest/
    repoURL: https://github.com/fractiunate/terraform-kaniko-k8s-service.git
    targetRevision: HEAD