---

apiVersion: v1
kind: Pod
metadata:
  name: kaniko-build-version
  namespace: kaniko
spec:
  automountServiceAccountToken: false
  securityContext:
    fsGroup: 65533 # to make SSH key readable
    fsGroupChangePolicy: "OnRootMismatch"
  containers:
    - name: kaniko-build
      image: gcr.io/kaniko-project/executor:latest
      # image gcr.io/kaniko-project/executor:debug
      args:
        - "--context=dir:///workspace/project"
        - "--destination=fractiunate/kaniko-demo:v1.0.3-kaniko"
        - "--dockerfile=Dockerfile"
      volumeMounts:
        - name: content-from-git
          mountPath: /workspace
        - name: dockerhub-registry-secret
          mountPath: /kaniko/.docker
  initContainers:
    - name: git-sync-build
      image: k8s.gcr.io/git-sync/git-sync:v3.4.0
      securityContext:
        runAsUser: 65533
      env:
        - name: GIT_SYNC_REPO
          value: git@github.com:fractiunate/private-project.git
        - name: GIT_SYNC_BRANCH
          value: main
        - name: GIT_SYNC_DEPTH
          value: "1"
        - name: GIT_SYNC_DEST
          value: "project"
        - name: GIT_SYNC_ONE_TIME
          value: "true"
        - name: GIT_SYNC_SSH
          value: "true"   
      volumeMounts:
        - name: git-secret
          mountPath: "/etc/git-secret"
        - name: content-from-git
          mountPath: /tmp/git
  restartPolicy: Never
  volumes:
    - name: content-from-git
      emptyDir: {}
    - name: kaniko-secret
      secret:
        secretName: kanikogitsecret
        defaultMode: 256
    - name: git-secret
      secret:
        secretName: kanikogitsecret
        defaultMode: 256
    - name: dockerhub-registry-secret
      secret:
        secretName: dockerhub-registry
        items:
          - key: .dockerconfigjson
            path: config.json
