apiVersion: v1
kind: Secret
metadata:
  name: argocd-repo-ssh-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:fractiunate/private-project.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACAzXsY04tgQMyCdNF1cTBFfcNd9fSBeLAED+q6RPrar9AAAAJiNsLfpjbC3
    6QAAAAtzc2gtZWQyNTUxOQAAACAzXsY04tgQMyCdNF1cTBFfcNd9fSBeLAED+q6RPrar9A
    AAAED48tqTAHj35264hLIoH0EJfmu42t0wUtZZy+9e+PKchjNexjTi2BAzIJ00XVxMEV9w
    1319IF4sAQP6rpE+tqv0AAAAFWQucmFoYWV1c2VyQGdtYWlsLmNvbQ==
    -----END OPENSSH PRIVATE KEY-----


# -----BEGIN OPENSSH PRIVATE KEY-----
# b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
# QyNTUxOQAAACAzXsY04tgQMyCdNF1cTBFfcNd9fSBeLAED+q6RPrar9AAAAJiNsLfpjbC3
# 6QAAAAtzc2gtZWQyNTUxOQAAACAzXsY04tgQMyCdNF1cTBFfcNd9fSBeLAED+q6RPrar9A
# AAAED48tqTAHj35264hLIoH0EJfmu42t0wUtZZy+9e+PKchjNexjTi2BAzIJ00XVxMEV9w
# 1319IF4sAQP6rpE+tqv0AAAAFWQucmFoYWV1c2VyQGdtYWlsLmNvbQ==
# -----END OPENSSH PRIVATE KEY-----
