apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kaniko-project
  namespace: kaniko
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: kaniko
    server: https://kubernetes.default.svc
  orphanedResources:
    warn: false
  sourceRepos:
  - '*'